FROM node:lts
ARG BRANCH=main

RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*

# Add Docker's official GPG key:
RUN apt-get update
RUN apt-get install --no-install-recommends -y ca-certificates curl
RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
RUN chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update

RUN apt-get install --no-install-recommends -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

RUN mkdir -p /nf

WORKDIR /nf

COPY . .
RUN rm -rf node_modules
RUN npm install

WORKDIR /nf/edgeFederatedClient
RUN rm -rf node_modules
RUN npm install

WORKDIR /nf/centralApi
RUN rm -rf node_modules
RUN npm install

WORKDIR /nf/centralFederatedClient
RUN rm -rf node_modules
RUN npm install

WORKDIR /nf/fileServer
RUN rm -rf node_modules
RUN npm install

WORKDIR /nf/desktopApp/reactApp
RUN rm -rf node_modules
RUN npm install

WORKDIR /nf/desktopApp/electronApp
RUN rm -rf node_modules
RUN npm install

WORKDIR /nf/edgeFederatedClient
RUN npm run build

WORKDIR /nf/desktopApp/reactApp
RUN npm run build

WORKDIR /nf/desktopApp/electronApp
RUN npm run build

WORKDIR /nf/centralApi
RUN npm run build
