// Docker may qualify Hub names and add the default tag in its status line.
const normalizeImageName = (name: string) => {
  const unqualified = name.replace(/^(?:docker\.io|index\.docker\.io)\//, '').replace(/^library\//, '')
  return unqualified.includes('@') || unqualified.split('/').pop()?.includes(':')
    ? unqualified
    : `${unqualified}:latest`
}

export const createDockerImageDetector = (imageName: string) => {
  let pending = ''
  let detected = false

  return (chunk: string): boolean => {
    if (detected) return true
    pending += chunk
    const lines = pending.split(/\r\n|[\r\n]/)
    pending = lines.pop() || ''
    for (const line of lines) {
      // Inspect output is generated by our probe of the selected image.
      if (/^\s*"Id":\s*"sha256:[a-f0-9]{64}",?\s*$/.test(line)) {
        detected = true
      }
      const status = /^Status: (?:Downloaded newer image|Image is up to date) for (\S+)\s*$/.exec(line)
      if (status && normalizeImageName(status[1]) === normalizeImageName(imageName)) {
        detected = true
      }
    }
    // Bound an incomplete line while retaining enough for an inspect/status line.
    pending = pending.slice(-16384)
    return detected
  }
}
